### PR TITLE
add test_async app

### PR DESCRIPTION
**Pull request by fay2003hiend**

### CODE REVIEW

**Comment by lenpuc** [comment]
Hi, Thanks for your contribution. 

Could you please give a brief summary what the pull request is for. Thanks

**Comment by fay2003hiend** [comment]
Hi

this is to just give user a straight forward working example instead of building a test app from README.
also it removes the hassle that user has to at least understand one kind of build system before they can use the library

**Comment by Entropy512** [comment]
It looks to me like right now it would always be compiled and isn't enabled/disabled with some sort of cmake directive.

When building this library for use in an embedded system, one doesn't want the test apps included, so the examples need to somehow be made optional as part of the build process.

**Comment by lenpuc** [comment]
Due to the current concerns i will not merge it.

However feel free to improve upon the mentioned issues.

**Comment by lenpuc** [comment]
I will close the current state of the PR. However feel free to open a new one if the changes are integrated

**Pull request closed without merging**
