### PR TITLE
fix compilation with boost 1.7

### PR DESCRIPTION
**Pull request by fay2003hiend**

### CODE REVIEW

**Comment by lenpuc** [comment]
Hi, Thanks for your contribution. 

Could you please give a brief summary what the pull request is fixing.
Furthermore is the fix backwards compatible? Does it still work with earlier versions?

**Comment by fay2003hiend** [comment]
Hi

this fix is tested compatible with both boost 1.6x (Ubuntu 18.04) and 1.7x (Ubuntu 20.04)
by the look of changes I think the impact is zero since it makes use of `m_io_service` instead of reading a context from `m_socket` (in 1.7x reading io_context from socket is changed)

**Comment by fay2003hiend** [comment]
there is a specific line removing `boost::ref` is because the latter `m_deadline_timer` constructor does not like wrapped context reference in 1.7x, removal of it should not cause any problem.

**Comment by lenpuc** [comment]
I'll test it, and if everything looks fine i'll merge it

**Comment by lenpuc** [comment]
Appears to be backward compatible. therefore it was merged

**Comment by fay2003hiend** [comment]
thank you

**Pull request merged**
